[workspace]
members = [
    "example",
    "libclapper-rs",
    "libclapper-rs/sys",
    "libclapper-gtk-rs",
    "libclapper-gtk-rs/sys",
]
resolver = "2"
exclude = [
  "gir",
  "gir-files-gtk",
  "gir-files-gstreamer"
]

[workspace.package]
edition = "2021"
version = "0.1.0"
